version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.71
    - 0.12.73
    - 0.12.74
    - 0.12.75
    - 0.12.77
    - 0.12.78
    - 0.12.80
    - 0.12.81
    - 0.12.82
    - 0.12.84
    - 0.12.85
  - dependency-name: phpstan/phpstan-symfony
    versions:
    - 0.12.17
    - 0.12.19
    - 0.12.21
    - 0.12.23
    - 0.12.24
    - 0.12.25
    - 0.12.26
    - 0.12.27
    - 0.12.28
  - dependency-name: gedmo/doctrine-extensions
    versions:
    - 3.0.3
    - 3.0.4
    - 3.0.5
  - dependency-name: rector/rector-prefixed
    versions:
    - 0.10.1
    - 0.10.11
    - 0.10.3
    - 0.10.4
    - 0.10.6
  - dependency-name: twilio/sdk
    versions:
    - 6.16.1
    - 6.17.0
    - 6.18.0
    - 6.19.0
    - 6.20.0
    - 6.21.0
    - 6.22.0
  - dependency-name: league/csv
    versions:
    - 9.7.1
  - dependency-name: stripe/stripe-php
    versions:
    - 7.69.0
    - 7.70.0
    - 7.71.0
    - 7.72.0
    - 7.73.0
    - 7.74.0
    - 7.75.0
    - 7.76.0
    - 7.77.0
  - dependency-name: symfony/phpunit-bridge
    versions:
    - 5.2.3
    - 5.2.4
    - 5.2.6
  - dependency-name: symfony/symfony
    versions:
    - 4.4.19
    - 4.4.20
    - 5.2.6
  - dependency-name: drupal/core-vendor-hardening
    versions:
    - 9.1.3
    - 9.1.4
    - 9.1.5
  - dependency-name: simshaun/recurr
    versions:
    - 4.0.5
  - dependency-name: edamov/pushok
    versions:
    - 0.13.0
  - dependency-name: box/spout
    versions:
    - 3.2.0
  - dependency-name: twig/twig
    versions:
    - 2.14.4
  - dependency-name: jaybizzle/crawler-detect
    versions:
    - 1.2.105
  - dependency-name: php-http/guzzle6-adapter
    versions:
    - 2.0.2
  - dependency-name: nyholm/psr7
    versions:
    - 1.4.0
  - dependency-name: twig/string-extra
    versions:
    - 3.2.1
    - 3.3.0
  - dependency-name: myclabs/php-enum
    versions:
    - 1.8.0
  - dependency-name: phpstan/phpstan-webmozart-assert
    versions:
    - 0.12.10
    - 0.12.11
    - 0.12.12
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: libphonenumber-js
    versions:
    - 1.9.10
    - 1.9.13
    - 1.9.14
    - 1.9.15
    - 1.9.16
    - 1.9.9
  - dependency-name: antd
    versions:
    - 4.14.0
    - 4.15.0
    - 4.15.2
  - dependency-name: "@babel/register"
    versions:
    - 7.12.13
    - 7.13.0
    - 7.13.14
  - dependency-name: cypress
    versions:
    - 6.6.0
    - 6.7.1
    - 6.8.0
    - 6.9.1
  - dependency-name: "@cubejs-client/react"
    versions:
    - 0.26.41
    - 0.26.46
    - 0.26.53
    - 0.26.58
    - 0.26.60
    - 0.26.61
    - 0.26.69
    - 0.26.93
    - 0.26.94
  - dependency-name: "@cubejs-client/core"
    versions:
    - 0.26.45
    - 0.26.53
    - 0.26.60
    - 0.26.61
    - 0.26.69
    - 0.26.93
    - 0.26.94
  - dependency-name: "@reduxjs/toolkit"
    versions:
    - 1.5.1
  - dependency-name: react-i18next
    versions:
    - 11.8.11
    - 11.8.13
  - dependency-name: eslint-webpack-plugin
    versions:
    - 2.5.3
    - 2.5.4
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
    - 7.23.2
  - dependency-name: react-phone-number-input
    versions:
    - 3.1.17
    - 3.1.18
    - 3.1.19
  - dependency-name: react-redux
    versions:
    - 7.2.3
    - 7.2.4
  - dependency-name: react-beautiful-dnd
    versions:
    - 13.1.0
  - dependency-name: codemirror
    versions:
    - 5.59.3
    - 5.59.4
    - 5.60.0
  - dependency-name: lottie-web
    versions:
    - 5.7.7
    - 5.7.8
  - dependency-name: qs
    versions:
    - 6.10.0
    - 6.10.1
  - dependency-name: "@ant-design/icons"
    versions:
    - 4.6.1
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.3.2
    - 24.3.4
    - 24.3.6
  - dependency-name: sequelize
    versions:
    - 5.22.3
    - 5.22.4
  - dependency-name: postcss-loader
    versions:
    - 5.2.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
    - 8.0.2
  - dependency-name: dropzone
    versions:
    - 5.7.4
    - 5.7.5
    - 5.7.6
    - 5.8.1
  - dependency-name: clipboard
    versions:
    - 2.0.8
  - dependency-name: html-loader
    versions:
    - 2.1.2
  - dependency-name: i18next
    versions:
    - 19.9.2
  - dependency-name: algoliasearch
    versions:
    - 4.8.5
    - 4.8.6
    - 4.9.0
    - 4.9.1
  - dependency-name: "@stripe/react-stripe-js"
    versions:
    - 1.3.0
    - 1.4.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: centrifuge
    versions:
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.5
  - dependency-name: chai
    versions:
    - 4.3.1
    - 4.3.3
  - dependency-name: jquery
    versions:
    - 3.6.0
  - dependency-name: cropperjs
    versions:
    - 1.5.11
  - dependency-name: core-js
    versions:
    - 3.10.2
    - 3.9.0
    - 3.9.1
  - dependency-name: "@stripe/stripe-js"
    versions:
    - 1.13.0
    - 1.13.1
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.13
    - 7.13.0
  - dependency-name: react-cropper
    versions:
    - 2.1.5
    - 2.1.6
    - 2.1.7
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: moment-timezone
    versions:
    - 0.5.33
  - dependency-name: ws
    versions:
    - 7.4.3
    - 7.4.5
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
  - dependency-name: react-dropzone
    versions:
    - 11.3.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.25.0
  - dependency-name: react-chartjs-2
    versions:
    - 2.11.2
  - dependency-name: redux
    versions:
    - 4.1.0
  - dependency-name: react-toastify
    versions:
    - 7.0.4
  - dependency-name: js-yaml
    versions:
    - 4.1.0
  - dependency-name: redis
    versions:
    - 3.1.1
  - dependency-name: pg
    versions:
    - 8.6.0
  - dependency-name: react-modal
    versions:
    - 3.13.1
  - dependency-name: react-split
    versions:
    - 2.0.10
  - dependency-name: styled-components
    versions:
    - 5.2.2
