monolog:
  # channels to use with autowire; https://symfony.com/doc/current/logging/channels_handlers.html#how-to-autowire-logger-channels
  channels:
    [
      'deprecation',
      'domain_event',
      'checkout',
      'database',
      'push_notification',
      'real_time_message',
      'transporter',
    ]
