services:

  _defaults:
    autowire: false
    autoconfigure: false
    public: true

  #
  # Command Handlers
  #

  coopcycle.domain.task.handler.start:
    class: AppBundle\Domain\Task\Handler\StartHandler
    arguments:
      $eventRecorder: '@event_recorder'
      $taskStateMachine: '@state_machine.task'
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\Start

  coopcycle.domain.task.handler.mark_as_done:
    class: AppBundle\Domain\Task\Handler\MarkAsDoneHandler
    arguments:
      - '@event_recorder'
      - '@translator'
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\MarkAsDone

  coopcycle.domain.task.handler.mark_as_failed:
    class: AppBundle\Domain\Task\Handler\MarkAsFailedHandler
    arguments:
      - '@event_recorder'
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\MarkAsFailed

  coopcycle.domain.task.handler.cancel:
    class: AppBundle\Domain\Task\Handler\CancelHandler
    arguments:
      - '@event_recorder'
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\Cancel

  coopcycle.domain.task.handler.delete_group:
    class: AppBundle\Domain\Task\Handler\DeleteGroupHandler
    arguments:
      - '@doctrine'
      - '@event_recorder'
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\DeleteGroup

  coopcycle.domain.task.handler.add_to_group:
    class: AppBundle\Domain\Task\Handler\AddToGroupHandler
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\AddToGroup

  coopcycle.domain.task.handler.remove_from_group:
    class: AppBundle\Domain\Task\Handler\RemoveFromGroupHandler
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\RemoveFromGroup

  coopcycle.domain.task.handler.restore:
    class: AppBundle\Domain\Task\Handler\RestoreHandler
    arguments:
      - '@event_recorder'
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\Restore

  coopcycle.domain.task.handler.reschedule:
    class: AppBundle\Domain\Task\Handler\RescheduleHandler
    arguments:
      - '@event_recorder'
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\Reschedule

  coopcycle.domain.task.handler.incident:
    class: AppBundle\Domain\Task\Handler\IncidentHandler
    arguments:
      - '@event_recorder'
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\Incident
  #
  # Reactors
  #

  coopcycle.domain.task.reactor.publish_live_update:
    class: AppBundle\Domain\Task\Reactor\PublishLiveUpdate
    arguments:
      - '@AppBundle\Service\LiveUpdates'
    tags:
      - name: event_subscriber
        subscribes_to: task:created
      - name: event_subscriber
        subscribes_to: task:assigned
      - name: event_subscriber
        subscribes_to: task:unassigned
      - name: event_subscriber
        subscribes_to: task:started
      - name: event_subscriber
        subscribes_to: task:done
      - name: event_subscriber
        subscribes_to: task:failed
      - name: event_subscriber
        subscribes_to: task:cancelled
      - name: event_subscriber
        subscribes_to: task_collections:updated
      - name: event_subscriber
        subscribes_to: task_list:updated
      - name: event_subscriber
        subscribes_to: task:rescheduled

  coopcycle.domain.task.reactor.send_email:
    class: AppBundle\Domain\Task\Reactor\SendEmail
    arguments:
      - '@coopcycle.email_manager'
    tags:
      - name: event_subscriber
        subscribes_to: task:done
      - name: event_subscriber
        subscribes_to: task:failed

  coopcycle.domain.task.reactor.send_sms:
    class: AppBundle\Domain\Task\Reactor\SendSms
    arguments:
      - '@coopcycle.settings_manager'
      - '@sylius.repository.order'
      - '@messenger.default_bus'
      - '@libphonenumber\PhoneNumberUtil'
      - '@router'
      - '@translator'
      - '%secret%'
    tags:
      - name: event_subscriber
        subscribes_to: task:started

  coopcycle.domain.task.reactor.trigger_webhook:
    class: AppBundle\Domain\Task\Reactor\TriggerWebhook
    arguments:
      - '@messenger.default_bus'
      - '@api_platform.iri_converter'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - name: event_subscriber
        subscribes_to: task:assigned
      - name: event_subscriber
        subscribes_to: task:started
      - name: event_subscriber
        subscribes_to: task:done
      - name: event_subscriber
        subscribes_to: task:failed

  coopcycle.domain.task.reactor.notify_urbantz:
    class: AppBundle\Domain\Task\Reactor\NotifyUrbantz
    arguments:
      - '@urbantz.client'
      - '@doctrine.orm.default_entity_manager'
      - '%secret%'
      - '@monolog.logger.urbantz'
    tags:
      - name: event_subscriber
        subscribes_to: task:assigned
      - name: event_subscriber
        subscribes_to: task:started
      - name: event_subscriber
        subscribes_to: task:done
      - name: event_subscriber
        subscribes_to: task:failed
