services:

  #
  # Command Handlers
  #

  coopcycle.domain.task.handler.mark_as_done:
    class: AppBundle\Domain\Task\Handler\MarkAsDoneHandler
    arguments:
      - '@event_recorder'
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\MarkAsDone

  coopcycle.domain.task.handler.mark_as_failed:
    class: AppBundle\Domain\Task\Handler\MarkAsFailedHandler
    arguments:
      - '@event_recorder'
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\MarkAsFailed

  coopcycle.domain.task.handler.cancel:
    class: AppBundle\Domain\Task\Handler\CancelHandler
    arguments:
      - '@event_recorder'
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\Cancel

  coopcycle.domain.task.handler.delete_group:
    class: AppBundle\Domain\Task\Handler\DeleteGroupHandler
    arguments:
      - '@doctrine'
      - '@event_recorder'
    tags:
      - name: command_handler
        handles: AppBundle\Domain\Task\Command\DeleteGroup

  #
  # Reactors
  #

  coopcycle.domain.task.reactor.publish_redis_message:
    class: AppBundle\Domain\Task\Reactor\PublishRedisMessage
    arguments:
      - '@serializer'
      - '@coopcycle.socket_io_manager'
    tags:
      - name: event_subscriber
        subscribes_to: task:created
      - name: event_subscriber
        subscribes_to: task:assigned
      - name: event_subscriber
        subscribes_to: task:unassigned
      - name: event_subscriber
        subscribes_to: task:done
      - name: event_subscriber
        subscribes_to: task:failed
      - name: event_subscriber
        subscribes_to: task:cancelled

  coopcycle.domain.task.reactor.send_email:
    class: AppBundle\Domain\Task\Reactor\SendEmail
    arguments:
      - '@coopcycle.email_manager'
      - '@coopcycle.settings_manager'
    tags:
      - name: event_subscriber
        subscribes_to: task:done
      - name: event_subscriber
        subscribes_to: task:failed

  coopcycle.domain.task.reactor.send_remote_push_notification:
    class: AppBundle\Domain\Task\Reactor\SendRemotePushNotification
    arguments:
      - '@coopcycle.remote_push_notification_manager'
      - '@api_platform.iri_converter'
      - '@fos_user.user_manager'
    tags:
      - name: event_subscriber
        subscribes_to: task:created
