imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: message_bus/order.yml }
    - { resource: message_bus/task.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: state_machine.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: "%coopcycle.locale%"
    locale_regex: fr|en|es|de

framework:
    #esi:             ~
    translator:      { fallbacks: ["en"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "en"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'
    globals:
        is_demo: "%is_demo%"
        sentry_public_dsn: "%sentry_public_dsn%"
        country_iso: "%country_iso%"
        cart_provider: '@coopcycle.cart_provider'
        settings_manager: "@coopcycle.settings_manager"
        piwik_site_id: "%piwik_site_id%"
        piwik_disabled: "%kernel.debug%"
        currency_context: "@sylius.context.currency"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            geography:
                class: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
                commented: false
            geometry:
                class: 'Jsor\Doctrine\PostGIS\Types\GeometryType'
                commented: false
            raster:
                class: 'Jsor\Doctrine\PostGIS\Types\RasterType'
                commented: false
            geojson:
                class: 'AppBundle\Doctrine\DBAL\Types\GeoJSONType'
                commented: true
            uuid:  Ramsey\Uuid\Doctrine\UuidType
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
            date_string: AppBundle\Doctrine\DBAL\Types\DateStringType
        mapping_types:
            _text: string

        # If you don't define this option and you haven't created your database yet,
        # you may get PDOException errors because Doctrine will try to guess
        # the database server version automatically and none is available.
        # http://symfony.com/doc/current/reference/configuration/doctrine.html
        # Should be fixed in next Doctrine version
        # https://github.com/doctrine/dbal/pull/2671
        server_version: 9.4

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            AppBundle:
                type: yml
        dql:
            string_functions:
                ST_DWithin: Jsor\Doctrine\PostGIS\Functions\ST_DWithin
                ST_GeomFromText: Jsor\Doctrine\PostGIS\Functions\ST_GeomFromText
                ST_Distance: Jsor\Doctrine\PostGIS\Functions\ST_Distance
                ST_GeomFromGeoJSON: Jsor\Doctrine\PostGIS\Functions\ST_GeomFromGeoJSON
                ST_AsText: Jsor\Doctrine\PostGIS\Functions\ST_AsText
            datetime_functions:
                date: DoctrineExtensions\Query\Mysql\Date
        filters:
            soft_deleteable:
                class:   Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/AppBundle/Api/Dto']
    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        ApiPlatform\Core\Exception\InvalidArgumentException: 400
        AppBundle\Api\Exception\BadRequestHttpException: 400

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    encryption: "%mailer_encryption%"
    spool:     { type: memory }

mailjet:
    api_key:    "%mailjet.api_key%"
    secret_key: "%mailjet.secret_key%"

# Nelmio CORS
nelmio_cors:
    defaults:
        allow_origin:   ["%cors_allow_origin%"]
        allow_methods:  ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
        allow_headers:  ["content-type", "authorization"]
        expose_headers: ["link"]
        max_age:        3600
    paths:
        '^/api/':
            allow_origin: ['*']

fos_user:
    db_driver: orm
    firewall_name: web
    user_class: AppBundle\Entity\ApiUser
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address:        "%transactional_address%"
        sender_name:    "%transactional_sender_name%"
    registration:
        form:
            type: AppBundle\Form\RegistrationType

lexik_jwt_authentication:
    private_key_path: "%jwt_private_key_path%"
    public_key_path:  "%jwt_public_key_path%"
    pass_phrase:      "%jwt_key_pass_phrase%"
    token_ttl:        "%jwt_token_ttl%"
    token_extractors:
        authorization_header:      # look for a token as Authorization Header
            enabled: true
            prefix:  Bearer
            name:    Authorization
        query_parameter:           # check token in query string parameter
            enabled: true
            name:    token

gesdinet_jwt_refresh_token:
    user_provider: fos_user.user_provider.username_email

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%redis_dsn%"
            options:
                prefix: "%database_name%:"
                # https://github.com/nrk/predis/issues/33
                read_write_timeout: 0

vich_uploader:
    db_driver: orm
    mappings:
        restaurant_image:
            uri_prefix: /images/restaurants
            upload_destination: '%kernel.root_dir%/../web/images/restaurants'
            namer: vich_uploader.namer_uniqid
            directory_namer:
                service: vich_uploader.directory_namer_subdir
                options:
                    chars_per_dir: 2
                    dirs: 2
        store_image:
            uri_prefix: /images/stores
            upload_destination: '%kernel.root_dir%/../web/images/stores'
            namer: vich_uploader.namer_uniqid
            directory_namer:
                service: vich_uploader.directory_namer_subdir
                options:
                    chars_per_dir: 2
                    dirs: 2

csa_guzzle:
    logger: true
    clients:
        osrm:
            config:
                base_uri: "http://%osrm_host%"
                lazy: true
        google_maps:
            config:
                base_uri: "https://maps.googleapis.com"
                lazy: true
        fcm:
            config:
                base_uri: "https://fcm.googleapis.com"
                lazy: true

sylius_taxation:
    driver: doctrine/orm

sylius_order:
    resources:
        order:
            classes:
                model: AppBundle\Entity\Sylius\Order
                repository: AppBundle\Entity\Sylius\OrderRepository
        order_item:
            classes:
                model: AppBundle\Entity\Sylius\OrderItem

sylius_product:
    resources:
        product:
            classes:
                model: AppBundle\Entity\Sylius\Product
        product_variant:
            classes:
                model: AppBundle\Entity\Sylius\ProductVariant
        product_option:
            classes:
                model: AppBundle\Entity\Sylius\ProductOption
        product_option_value:
            classes:
                model: AppBundle\Entity\Sylius\ProductOptionValue

sylius_taxonomy:
    resources:
        taxon:
            classes:
                model: AppBundle\Entity\Sylius\Taxon
                # interface: Sylius\Component\Taxonomy\Model\TaxonInterface

sylius_locale:
    locale: "%locale%"

sylius_currency:
    driver: doctrine/orm

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/bin/wkhtmltoimage
        options:    []

m6_statsd:
    servers:
        default:
            address: 'udp://%statsd_host%'
            port: "%statsd_port%"
    clients:
        default:
            servers: ["default"]

knp_paginator:
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'

sonata_seo:
    encoding: UTF-8
    page:
        title: CoopCycle
        metas:
            name:
                robots: index, follow
            http-equiv:
                'Content-Type': text/html; charset=utf-8
            charset:
                UTF-8: ''

command_bus:
    logging: ~

event_bus:
    event_name_resolver_strategy: named_message
    logging: ~

jmose_command_scheduler:
    # https://github.com/J-Mose/CommandSchedulerBundle/issues/108
    monitor_mail_subject: 'cronjob monitoring %%s, %%s'
