imports:
    - { resource: config.yml }

framework:
    assets:
        json_manifest_path: "%kernel.project_dir%/web/manifest.json"
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  rotating_file
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 7
        mailer:
            level:    error
            type:     rotating_file
            path:     '%kernel.logs_dir%/mailer.%kernel.environment%.log'
            max_files: 7
            channels: [mailer]
        console:
            type:  console

fos_user:
    registration:
        confirmation:
            enabled: true

sentry:
    dsn: '%sentry_dsn%'

