imports:
    - { resource: config_dev.yml }

parameters:
    tile38_fleet_key: '%database_name%_test:fleet'
    tile38_doorstep_chan_namespace: '%database_name%_test'

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    cache:
        prefix_seed: "%database_name%_test"
        app: cache.adapter.array

doctrine:
    dbal:
        dbname:   "%database_name%_test"

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: "%env(COOPCYCLE_REDIS_DSN)%/1"
            options:
                prefix: "%database_name%_test:"

oneup_flysystem:
    adapters:
        assets:
            local:
                directory: '/tmp'
        product_images:
            local:
                directory: '/tmp'
        restaurant_images:
            local:
                directory: '/tmp'
        store_images:
            local:
                directory: '/tmp'
        task_images:
            local:
                directory: '/tmp'
        receipts:
            local:
                directory: '/tmp'
        task_imports:
            local:
                directory: '/tmp'
        product_imports:
            local:
                directory: '/tmp'

services:
    AppBundle\EventListener\CarbonListener:
        arguments:
            - '@snc_redis.default'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    AppBundle\Fixtures\AliceDataFixtures\SettingsProcessor:
        arguments:
          - '@coopcycle.settings_manager'
        tags:
            - { name: fidry_alice_data_fixtures.processor }
