imports:
    - { resource: config.yml }

framework:
    php_errors:
        log: true
        throw: false
    assets:
        json_manifest_path: "%kernel.project_dir%/web/build/manifest.json"
    # https://symfony.com/doc/current/cache.html#configuring-cache-with-frameworkbundle
    # https://github.com/symfony/demo/blob/master/config/packages/prod/doctrine.yaml
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc
    session:
        cookie_secure: true

parameters:
    router.request_context.scheme: 'https'
    nucleos_profile.registration.confirmation.enabled: true

# https://github.com/doctrine/DoctrineBundle/releases/tag/2.0.1
# https://symfony.com/blog/new-in-doctrinebundle-1-11-0
# https://github.com/symfony/demo/blob/master/config/packages/prod/doctrine.yaml
doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: rotating_file
            path: "%env(APP_LOG_DIR)%/%kernel.environment%.log"
            level: debug
            formatter: monolog.formatter.json
            max_files: 7
            channels: ["!api", "!stripe", "!loopeat"]
        api:
            type: rotating_file
            path: "%env(APP_LOG_DIR)%/api.%kernel.environment%.log"
            level: info
            formatter: monolog.formatter.json
            max_files: 7
            channels: [api]
        messenger:
            type: rotating_file
            path: "%env(APP_LOG_DIR)%/messenger.%kernel.environment%.log"
            level: debug
            formatter: monolog.formatter.json
            max_files: 7
            channels: [messenger]
        fee_calculation:
            type: rotating_file
            path: "%env(APP_LOG_DIR)%/fee_calculation.%kernel.environment%.log"
            level: info
            formatter: monolog.formatter.json
            max_files: 7
            channels: [fee_calculation]
        timing:
            type: rotating_file
            path: "%env(APP_LOG_DIR)%/timing.%kernel.environment%.log"
            level: info
            max_files: 7
            channels: [timing]
        geofencing:
            type: rotating_file
            path: "%env(APP_LOG_DIR)%/geofencing.%kernel.environment%.log"
            level: info
            formatter: monolog.formatter.json
            max_files: 7
            channels: [geofencing]
        stripe:
            type: rotating_file
            path: "%env(APP_LOG_DIR)%/stripe.%kernel.environment%.log"
            level: info
            max_files: 7
            channels: [stripe]
        loopeat:
            type: rotating_file
            path: "%env(APP_LOG_DIR)%/loopeat.%kernel.environment%.log"
            level: info
            max_files: 7
            channels: [loopeat]
        urbantz:
            type: rotating_file
            path: "%env(APP_LOG_DIR)%/urbantz.%kernel.environment%.log"
            level: info
            max_files: 7
            channels: [urbantz]
        dabba:
            type: rotating_file
            path: "%env(APP_LOG_DIR)%/dabba.%kernel.environment%.log"
            level: info
            max_files: 7
            channels: [dabba]
        console:
            type:  console

nucleos_profile:
    registration:
        confirmation:
            enabled: true

services:
    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - Symfony\Component\Security\Core\Exception\AccessDeniedException
                    - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
                    - ApiPlatform\Core\Bridge\Symfony\Validator\Exception\ValidationException

sentry:
    dsn: '%sentry_public_dsn%'
    options:
        tags:
            coopcycle_app_name: '%env(COOPCYCLE_APP_NAME)%'
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'
