imports:
    - { resource: config.yml }

framework:
    assets:
        json_manifest_path: "%kernel.project_dir%/web/manifest.json"
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc

parameters:
    router.request_context.scheme: 'https'

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

services:
    AppBundle\Monolog\Processor\RequestResponseProcessor:
        tags:
            - { name: monolog.processor, channel: api }
    apns_php.logger:
        class: AppBundle\Utils\ApnsPHPLogger
        arguments: [ '@logger' ]
    apns_php.push:
        class: \ApnsPHP_Push
        arguments:
            - 0
            - "%apns_certificate_file%"
        calls:
            - method: setLogger
              arguments:
                  - '@apns_php.logger'

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  rotating_file
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 7
            channels: ["!api", "!stripe"]
        api:
            type: predis
            redis:
                host: '%redis_dsn%'
                key_name: '%database_name%:api:logs'
            level: info
            formatter: Monolog\Formatter\JsonFormatter
            channels: [api]
        stripe:
            type: rotating_file
            path: "%kernel.logs_dir%/stripe.%kernel.environment%.log"
            level: info
            max_files: 7
            channels: [stripe]
        mailer:
            level:    error
            type:     rotating_file
            path:     '%kernel.logs_dir%/mailer.%kernel.environment%.log'
            max_files: 7
            channels: [mailer]
        console:
            type:  console

fos_user:
    registration:
        confirmation:
            enabled: true

sentry:
    dsn: '%sentry_public_dsn%'
    options:
        # https://github.com/getsentry/sentry-symfony#step-3-configure-the-sdk
        # https://docs.sentry.io/platforms/php/#php-specific-options
        excluded_exceptions:
            - Symfony\Component\Security\Core\Exception\AccessDeniedException

# see
# https://github.com/liip/LiipImagineBundle/issues/1018
# https://github.com/liip/LiipImagineBundle/issues/1144
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/../../shared/web'
    loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.project_dir%/../../shared/web'
                    - '%kernel.project_dir%/web'
