winzou_state_machine:
    sylius_order:
        class: "%sylius.model.order.class%"
        property_path: state
        graph: sylius_order
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            new: ~
            cancelled: ~
            fulfilled: ~
            accepted: ~
            refused: ~
            ready: ~
        transitions:
            create:
                from: [cart]
                to: new
            cancel:
                from: [new, accepted]
                to: cancelled
            fulfill:
                from: [accepted, ready]
                to: fulfilled
            accept:
                from: [new]
                to: accepted
            refuse:
                from: [new]
                to: refused
            ready:
                from: [accepted]
                to: ready
    sylius_payment:
        class: AppBundle\Entity\StripePayment
        property_path: state
        graph: sylius_payment
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            new: ~
            authorized: ~
            processing: ~
            completed: ~
            failed: ~
            cancelled: ~
            void: ~
            refunded: ~
        transitions:
            create:
                from: [cart]
                to: new
            authorize:
                from: [cart, new]
                to: authorized
            process:
                from: [new]
                to: processing
            complete:
                from: [new, authorized, processing]
                to: completed
            fail:
                from: [cart, new, authorized]
                to: failed
            cancel:
                from: [new]
                to: cancelled
            refund:
                from: [completed]
                to: refunded
            void:
                from: [new, processing]
                to: void
    stripe_transfer:
        class: AppBundle\Entity\StripeTransfer
        property_path: state
        graph: stripe_transfer
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            completed: ~
            failed: ~
            refunded: ~
        transitions:
            complete:
                from: [new]
                to: completed
            fail:
                from: [new]
                to: failed
            refund:
                from: [completed]
                to: refunded
