version: 2
jobs:
  docker_compose:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Pull containers
          command: docker-compose pull
      - run:
          name: Build containers
          command: docker-compose build
      - run:
          name: Start containers
          command: docker-compose up -d
          background: true
      - run:
          name: Wait for PHP-FPM
          command: until docker inspect --format='{{ .State.Health.Status }}' $(docker-compose ps -q php) | grep -wq healthy; do sleep 5; done
      - run:
          name: Install app
          command: make install

workflows:
  version: 2
  docker_compose:
    jobs:
      - docker_compose
