admin_deliveries_new:
  path: /admin/deliveries/new
  defaults:
      _controller: AppBundle:Admin:newDelivery
      layout: AppBundle::admin.html.twig
      routes:
          success: admin_deliveries
          calculate_price: admin_deliveries_calculate_price
  methods:  [ GET, POST ]

admin_deliveries_calculate_price:
    path:     /admin/deliveries/calculate-price
    defaults: { _controller: AppBundle:Admin:calculateDeliveryPrice }

admin_delivery:
  path: /admin/deliveries/{id}
  defaults:
      _controller: AppBundle:Admin:editDelivery
      layout: AppBundle::admin.html.twig
      routes:
          success: admin_deliveries
          calculate_price: admin_deliveries_calculate_price
  methods:  [ GET, POST ]

admin_order_invoice:
    path:     /admin/orders/CPCCL-{number}.pdf
    defaults: { _controller: AppBundle:Admin:orderInvoice }
    methods:  [ GET ]

admin_order:
    path:     /admin/orders/{id}
    defaults: { _controller: AppBundle:Admin:order }
    methods:  [ GET, POST ]

admin_orders:
    path:     /admin/orders
    defaults:
        _controller: AppBundle:Admin:orderList
        layout: AppBundle::admin.html.twig
        template: AppBundle:Admin:orders.html.twig
        routes:
            restaurant: admin_restaurant
            order_invoice: admin_order_invoice
            order: admin_order
    methods:  [ GET ]

admin_restaurant_new:
    path: /admin/restaurants/new
    defaults:
        _controller: AppBundle:Admin:newRestaurant
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:form.html.twig
        routes:
            success: admin_restaurant
            restaurants: admin_restaurants
            menu_taxons: admin_restaurant_menu_taxons
            menu_taxon: admin_restaurant_menu_taxon
            products: admin_restaurant_products
            product_options: admin_restaurant_product_options
            dashboard: admin_restaurant_dashboard
            planning: admin_restaurant_planning
    methods: [ GET, POST ]

admin_restaurant:
    path: /admin/restaurants/{id}
    defaults:
        _controller: AppBundle:Admin:restaurant
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:form.html.twig
        routes:
            success: admin_restaurant
            restaurants: admin_restaurants
            menu_taxons: admin_restaurant_menu_taxons
            menu_taxon: admin_restaurant_menu_taxon
            products: admin_restaurant_products
            product_options: admin_restaurant_product_options
            dashboard: admin_restaurant_dashboard
            planning: admin_restaurant_planning
    methods: [ GET, POST ]

admin_restaurants:
    path: /admin/restaurants
    defaults:
        _controller: AppBundle:Admin:restaurantList
        layout: AppBundle::admin.html.twig
        template: AppBundle:Admin:restaurants.html.twig
        routes:
            dashboard: admin_restaurant_dashboard
            menu_taxon: admin_restaurant_menu_taxon
            menu_taxons: admin_restaurant_menu_taxons
            restaurant: admin_restaurant
    methods: [ GET ]

admin_restaurant_menu_taxons:
    path: /admin/restaurants/{id}/menus
    defaults:
        _controller: AppBundle:Admin:restaurantMenuTaxons
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:menuTaxons.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            menu: admin_restaurant_menu_taxon
            menu_activate: admin_restaurant_menu_taxon_activate
            new_menu: admin_restaurant_new_menu_taxon
    methods: [ GET ]

admin_restaurant_new_menu_taxon:
    path: /admin/restaurants/{id}/menus/new
    defaults:
        _controller: AppBundle:Admin:newRestaurantMenuTaxon
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:menuTaxon.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            menu_taxons: admin_restaurant_menu_taxons
            menu_taxon: admin_restaurant_menu_taxon
            success: admin_restaurant_menu_taxons
    methods: [ GET, POST ]

admin_restaurant_menu_taxon:
    path: /admin/restaurants/{restaurantId}/menus/{menuId}
    defaults:
        _controller: AppBundle:Admin:restaurantMenuTaxon
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:menuTaxon.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            menu_taxons: admin_restaurant_menu_taxons
            products: admin_restaurant_products
            delete_section: admin_delete_restaurant_menu_taxon_child
            success: admin_restaurant_menu_taxons
    methods: [ GET, POST ]

admin_restaurant_menu_taxon_activate:
    path: /admin/restaurants/{restaurantId}/menus/{menuId}/activate
    defaults:
        _controller: AppBundle:Admin:activateRestaurantMenuTaxon
        layout: AppBundle::admin.html.twig
        routes:
            menu_taxons: admin_restaurant_menu_taxons
    methods: [ POST ]

admin_delete_restaurant_menu_taxon_child:
    path: /admin/restaurants/{restaurantId}/menus/{menuId}/sections/{sectionId}/delete
    defaults:
        _controller: AppBundle:Admin:deleteRestaurantMenuTaxonChild
        layout: AppBundle::admin.html.twig
        routes:
            menu_taxon: admin_restaurant_menu_taxon
    methods: [ POST ]

admin_restaurant_products:
    path: /admin/restaurants/{id}/products
    defaults:
        _controller: AppBundle:Admin:restaurantProducts
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:products.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            product: admin_restaurant_product
            new_product: admin_restaurant_product_new
    methods: [ GET ]

admin_restaurant_product_new:
    path: /admin/restaurants/{id}/products/new
    defaults:
        _controller: AppBundle:Admin:newRestaurantProduct
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:product.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            products: admin_restaurant_products

admin_restaurant_product:
    path: /admin/restaurants/{restaurantId}/products/{productId}
    defaults:
        _controller: AppBundle:Admin:restaurantProduct
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:product.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            products: admin_restaurant_products

admin_restaurant_planning:
    path: /admin/restaurants/{id}/planning
    defaults:
        _controller: AppBundle:Admin:restaurantPlanning
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:planning.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            success: admin_restaurant_planning
    methods: [ GET, POST ]

admin_restaurant_product_options:
    path: /admin/restaurants/{id}/product-options
    defaults:
        _controller: AppBundle:Admin:restaurantProductOptions
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:productOptions.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            product_option: admin_restaurant_product_option
            new_product_option: admin_restaurant_product_option_new
    methods: [ GET ]

admin_restaurant_product_option_new:
    path: /admin/restaurants/{id}/product-options/new
    defaults:
        _controller: AppBundle:Admin:newRestaurantProductOption
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:productOption.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            product_options: admin_restaurant_product_options
    methods: [ GET, POST ]

admin_restaurant_product_option:
    path: /admin/restaurants/{restaurantId}/product-options/{optionId}
    defaults:
        _controller: AppBundle:Admin:restaurantProductOption
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:productOption.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            product_options: admin_restaurant_product_options
    methods: [ GET, POST ]

admin_restaurant_dashboard:
    path: /admin/restaurants/{restaurantId}/dashboard
    defaults:
        _controller: AppBundle:Admin:restaurantDashboard
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:dashboard.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            dashboard: admin_restaurant_dashboard
            dashboard_order: admin_restaurant_dashboard_order
            order_accept: admin_restaurant_dashboard_order_accept
            order_refuse: admin_restaurant_dashboard_order_refuse
            order_cancel: admin_restaurant_dashboard_order_cancel
            order_ready: admin_restaurant_dashboard_order_ready
            user_details: user
    methods: [ GET ]

admin_restaurant_dashboard_order:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}
    defaults:
        _controller: AppBundle:Admin:restaurantDashboardOrder
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:dashboard.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            dashboard: admin_restaurant_dashboard
            dashboard_order: admin_restaurant_dashboard_order
            order_accept: admin_restaurant_dashboard_order_accept
            order_refuse: admin_restaurant_dashboard_order_refuse
            order_cancel: admin_restaurant_dashboard_order_cancel
            order_ready: admin_restaurant_dashboard_order_ready
            user_details: user
    methods: [ GET ]

admin_restaurant_dashboard_order_accept:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/accept
    defaults:
        _controller: AppBundle:Admin:acceptOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_restaurant_dashboard_order_refuse:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/refuse
    defaults:
        _controller: AppBundle:Admin:refuseOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_restaurant_dashboard_order_ready:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/ready
    defaults:
        _controller: AppBundle:Admin:readyOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_restaurant_dashboard_order_cancel:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/cancel
    defaults:
        _controller: AppBundle:Admin:cancelOrderFromDashboard
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_orders_order_cancel:
    path: /admin/orders/{id}/cancel
    defaults:
        _controller: AppBundle:Admin:cancelOrder
        redirect_route: admin_orders
    methods: [ POST ]

admin_stores:
    path: /admin/stores
    defaults:
        _controller: AppBundle:Admin:storeList
        layout: AppBundle::admin.html.twig
        template: AppBundle:Admin:stores.html.twig
        routes:
            store: admin_store
            store_delivery: admin_store_delivery
    methods:  [ GET ]

admin_store_new:
    path: /admin/stores/new
    defaults:
        _controller: AppBundle:Admin:newStore
        layout: AppBundle::admin.html.twig
        routes:
            stores: admin_stores
            store_delivery: admin_store_delivery
    methods:  [ GET, POST ]

admin_store:
    path: /admin/stores/{id}
    defaults:
        _controller: AppBundle:Admin:store
        layout: AppBundle::admin.html.twig
        routes:
            stores: admin_stores
            store_delivery: admin_store_delivery
            store_api_keys: admin_store_api_keys
    methods:  [ GET, POST ]

admin_store_delivery:
    path: /admin/stores/{id}/deliveries/new
    defaults:
        _controller: AppBundle:Admin:newStoreDelivery
        layout: AppBundle::admin.html.twig
        routes:
            stores: admin_stores
            store: admin_store
            success: admin_orders
            calculate_price: admin_deliveries_calculate_price
    methods:  [ GET, POST ]

admin_store_api_keys:
    path: /admin/stores/{id}/api-keys
    defaults:
        _controller: AppBundle:Admin:apiKeys
        layout: AppBundle::admin.html.twig
        routes:
            stores: admin_stores
            success: admin_store_api_keys
    methods:  [ GET, POST ]

admin_tag_new:
    path: /admin/settings/tags/new
    defaults:
        _controller: AppBundle:Tag:newTag
        template: AppBundle:Admin:tag.html.twig
        redirect_route: admin_tags

admin_tag:
    path: /admin/settings/tags/{slug}
    defaults:
        _controller: AppBundle:Tag:tag
        template: AppBundle:Admin:tag.html.twig
        redirect_route: admin_tags
