vegetarian: noto:seedling
french: fxemoji:franceflag
fast_food: twemoji:french-fries
vegan: lucide:vegan
burgers: twemoji:hamburger
home_made: streamline-emojis:woman-cook-2
mediterranean: noto:shallow-pan-of-food
italian: fxemoji:italianflag
poke_bowl: fluent-emoji-flat:green-salad
pizza: noto:pizza
asian: twemoji:steaming-bowl
tapas: noto:woman-dancing
sandwiches: noto:sandwich
healthy: noto:red-apple
sushi: twemoji:sushi
japanese: fxemoji:japanesedolls
african: academicons:africarxiv
salad: twemoji:green-salad
bistro: noto-v1:wine-glass
soup: twemoji:bowl-with-spoon
lebanese: emojione:flag-for-lebanon
chicken: emojione:chicken
