# afghan: Afghan
african: academicons:africarxiv
# albanian: Albanian
algerian: emojione:flag-for-algeria
# alsatian: Alsatian
american: circle-flags:us
# andalusian: Andalusian
# aragonese: Aragonese
# argentine: Argentine
# armenian: Armenian
asian: twemoji:steaming-bowl
# asturian: Asturian
# australian: Australian
# austrian: Austrian
# auvergne: Auvergne
# bagels: Bagels
# bakery: Bakery
# bangladeshi: Bangladeshi
# barbecue: Barbecue
# basque: Basque
# belgian: Belgian
bento: noto-v1:bento-box
bistro: noto-v1:wine-glass
# brazilian: Brazilian
# british: British
burgers: twemoji:hamburger
# burgundy: Burgundy
# burmese: Burmese
# cafe: Cafe
# cajun: Cajun
# californian: Californian
# calzones: Calzones
# cambodian: Cambodian
# canadian: Canadian
# canary: Canary
# caribbean: Caribbean
# castiza: Castiza
# catalan: Catalan
# cheesesteaks: Cheesesteaks
chicken: emojione:chicken
# chilean: Chilean
chinese: emojione:flag-for-china
# chowder: Chowder
# coffee: Coffee
# colombian: Colombian
# contemporary: Contemporary
# continental: Continental
# corsica: Corsica
# creole: Creole
crepes: noto:pancakes
# cuban: Cuban
# czech: Czech
# deli: Deli
# dim_sum: Dim Sum
# diner: Diner
# dominican: Dominican
donuts: token-branded:donut
# dutch: Dutch
# eastern_european: Eastern European
# eclectic: Eclectic
# ecuadorean: Ecuadorean
# egyptian: Egyptian
# english: English
# ethiopian: Ethiopian
# european: European
# extremaduran: Extremaduran
fast_food: twemoji:french-fries
# filipino: Filipino
# fish_and_chips: Fish and Chips
# fondue: Fondue
french: fxemoji:franceflag
# frozen_yogurt: Frozen Yogurt
# fusion: Fusion
# galician: Galician
# gastronomic: Gastronomic
# gastropub: Gastropub
# german: German
gluten_free: healthicons:gluten-free-outline
# greek: Greek
# grill: Grill
# gyros: Gyros
# haitian: Haitian
halal: streamline-color:islam-flat
# hand_made: Hand Made
# hawaiian: Hawaiian
healthy: noto:red-apple
home_made: streamline-emojis:woman-cook-2
hot_dogs: noto:hot-dog
ice_cream: noto:ice-cream
# indian: Indian
# indonesian: Indonesian
# international: International
# irish: Irish
# israeli: Israeli
italian: fxemoji:italianflag
# jamaican: Jamaican
japanese: fxemoji:japanesedolls
# juices: Juices
kebab: noto:taco
# korean_barbeque: Korean Barbeque
# korean: Korean
# kosher: Kosher
# latin_american: Latin American
# latin: Latin
lebanese: emojione:flag-for-lebanon
# levantine: Levantine
local: glyphs-poly:map-marker-line
# lyonnais: Lyonnais
# malaysian: Malaysian
# manchega: Manchega
mediterranean: noto:shallow-pan-of-food
mexican: emojione:flag-for-mexico
# middle_eastern: Middle Eastern
# mongolian: Mongolian
# moroccan: Moroccan
# nepalese: Nepalese
# noodle_bar: Noodle Bar
# norwegian: Norwegian
# organic: Organic
# oysters: Oysters
# pacific_rim: Pacific Rim
# pakistani: Pakistani
# pan_asian: Pan Asian
pasta: noto:spaghetti
# pastries: Pastries
# persian: Persian
# peruvian: Peruvian
# pho: Pho
pizza: noto:pizza
# plant_based: Plant Based
poke_bowl: fluent-emoji-flat:green-salad
# polish: Polish
# polynesian: Polynesian
# portuguese: Portuguese
# provencal: Proven√ßal
# pub_food: Pub Food
# puerto_rican: Puerto Rican
# raw: Raw
# ribs: Ribs
rice_based: twemoji:taco
# russian: Russian
salad: twemoji:green-salad
# salvadoran: Salvadoran
sandwiches: noto:sandwich
# savoy: Savoy
# scandinavian: Scandinavian
seafood: noto:shrimp
# senegalese: Senegalese
# singaporean: Singaporean
# smoothies: Smoothies
# soul_food: Soul Food
soup: twemoji:bowl-with-spoon
# south_african: South African
# south_american: South American
# southern: Southern
# south_pacific: South Pacific
# southwestern: Southwestern
spanish: emojione:flag-for-spain
# steakhouse: Steakhouse
# steak: Steak
steetfood: fluent-emoji-flat:cityscape-at-dusk
# subs: Subs
sushi: twemoji:sushi
# taiwanese: Taiwanese
tapas: noto:woman-dancing
tea: emojione:teacup-without-handle
tex_mex: emojione:flag-for-mexico
# thai: Thai
# tibetan: Tibetan
# traditional: Traditional
# tunisian: Tunisian
# turkish: Turkish
# ukrainian: Ukrainian
vegan: lucide:vegan
vegetarian: noto:seedling
# venezuelan: Venezuelan
# vietnamese: Vietnamese
# wings: Wings
# wraps: Wraps
