AppBundle\Entity\User:
  attributes:
    username:
      groups: ['user', 'order']
    email:
      groups: ['user', 'order']
    addresses:
      groups: ['user']
    telephone:
      groups: ['user', 'order', 'user_update']
    roles:
      groups: ['user']
    givenName:
      groups: ['order']
    familyName:
      groups: ['order']

AppBundle\Entity\Sylius\Customer:
  attributes:
    username:
      groups: ['customer', 'order']
    email:
      groups: ['customer', 'order']
    telephone:
      groups: ['customer', 'order', 'customer_update']
    phoneNumber:
      groups: ['customer', 'order', 'customer_update']

AppBundle\Entity\Sylius\Taxon:
  attributes:
    code:
      groups: ['restaurant_menu', 'restaurant_menus']
    name:
      groups: ['restaurant_menu', 'restaurant_menus']

Sylius\Component\Order\Model\Order:
  attributes:
    id:
      groups: ['order']
    restaurant:
      groups: ['order', 'order_create', 'cart', 'order_update']
    shippingAddress:
      groups: ['order', 'order_create', 'cart', 'order_update']
    shippedAt:
      groups: ['order', 'order_create', 'cart', 'order_update']
    shippingTimeRange:
      groups: ['order', 'order_create', 'cart', 'order_update']
    customer:
      groups: ['order', 'cart']
    items:
      groups: ['order', 'order_create', 'cart']
    total:
      groups: ['order', 'cart']
    number:
      groups: ['order']
    itemsTotal:
      groups: ['order', 'cart']
    taxTotal:
      groups: ['order']
    state:
      groups: ['order']
    notes:
      groups: ['order', 'cart', 'order_update']
    createdAt:
      groups: ['order']
    timeline:
      groups: ['order_timeline']
    preparationExpectedAt:
      groups: ['order']
    pickupExpectedAt:
      groups: ['order']
    reusablePackagingEnabled:
      groups: ['order', 'cart', 'order_update']
    reusablePackagingPledgeReturn:
      groups: ['order', 'cart', 'order_update']
    takeaway:
      groups: ['order']
    fulfillmentMethod:
      groups: ['cart', 'order_update']

Sylius\Component\Order\Model\OrderItem:
  attributes:
    id:
      groups: ['order', 'cart']
    quantity:
      groups: ['order', 'cart']
    total:
      groups: ['order', 'cart']
    unitPrice:
      groups: ['order', 'cart']

AppBundle\Entity\Sylius\OrderTimeline:
  attributes:
    preparationExpectedAt:
      groups: ['order_timeline']
    pickupExpectedAt:
      groups: ['order_timeline']
    dropoffExpectedAt:
      groups: ['order_timeline']

Sylius\Component\Product\Model\Product:
  attributes:
    id:
      groups: ['product']
    name:
      groups: ['product']
    description:
      groups: ['product']
    code:
      groups: ['product']
    enabled:
      groups: ['product', 'product_update']

AppBundle\Entity\LocalBusiness\FulfillmentMethod:
  attributes:
    type:
      groups: ['restaurant']
    openingHours:
      groups: ['restaurant']
    enabled:
      groups: ['restaurant']
