# https://www.avalara.com/vatlive/en/vat-rates/international-vat-and-gst-rates.html

service:
  rates:
    be:
      standard: 0.21
    ca-bc:
      gst: 0.05
    de:
      standard: 0.19
    es:
      standard: 0.21
    fr:
      standard: 0.20
    gb:
      standard: 0.20
    pl:
      standard: 0.23
    ar:
      standard: 0.21
    mx:
      standard: 0.16
    au:
      gst: 0.10
    se:
      standard: 0.25
    dk:
      standard: 0.25
    it:
      standard: 0.22
    cl:
      standard: 0.19
    hu:
      standard: 0.27
    pt:
      standard: 0.23

service_tax_exempt:
  rates:
    be:
      zero: 0.0
    ca-bc:
      zero: 0.0
    de:
      zero: 0.0
    es:
      zero: 0.0
    fr:
      zero: 0.0
    gb:
      zero: 0.0
    pl:
      zero: 0.0
    ar:
      zero: 0.0
    au:
      zero: 0.0
    mx:
      zero: 0.0
    se:
      zero: 0.0
    dk:
      zero: 0.0
    it:
      zero: 0.0
    cl:
      zero: 0.0
    hu:
      zero: 0.0
    pt:
      zero: 0.0

drink:
  rates:
    es:
      reduced: 0.1
    fr:
      reduced: 0.055

drink_alcohol:
  rates:
    be:
      standard: 0.21
    ca-bc:
      gst: 0.05
      pst: 0.10
    de:
      standard: 0.19
    es:
      standard: 0.21
    fr:
      standard: 0.20
    gb:
      standard: 0.20
    pl:
      standard: 0.23

food_takeaway:
  rates:
    be:
      reduced: 0.06
    de:
      standard: 0.19
    es:
      intermediary: 0.1
    fr:
      intermediary: 0.1
    gb:
      zero: 0.0
    pl:
      intermediary: 0.08

base_standard:
  rates:
    be:
      standard: 0.21
    ca-bc:
      gst: 0.05
      pst: 0.07
    de:
      standard: 0.19
    es:
      standard: 0.21
    fr:
      standard: 0.20
    gb:
      standard: 0.20
    pl:
      standard: 0.23
    ar:
      standard: 0.21
    au:
      gst: 0.10
    mx:
      standard: 0.16
    se:
      standard: 0.25
    dk:
      standard: 0.25
    it:
      standard: 0.22
    cl:
      standard: 0.19
    hu:
      standard: 0.27
    pt:
      standard: 0.23

base_intermediary:
  rates:
    be:
      intermediary: 0.12
    ca-bc:
      gst: 0.05
      pst: 0.00
    es:
      intermediary: 0.1
    fr:
      intermediary: 0.1
    gb:
      intermediary: 0.05
    pl:
      intermediary: 0.08
    ar:
      intermediary: 0.105
    se:
      intermediary: 0.12
    it:
      intermediary: 0.1
    hu:
      intermediary: 0.18
    pt:
      intermediary: 0.13

base_reduced:
  rates:
    be:
      reduced: 0.06
    de:
      reduced: 0.07
    es:
      reduced: 0.04
    fr:
      reduced: 0.055
    pl:
      reduced: 0.05
    ar:
      reduced: 0.025
    mx:
      reduced: 0.08
    se:
      reduced: 0.06
    it:
      reduced: 0.04
    hu:
      reduced: 0.05
    pt:
      reduced: 0.06

base_exempt:
  rates:
    be:
      zero: 0.00
    ca-bc:
      gst: 0.00
      pst: 0.00
    de:
      zero: 0.00
    es:
      zero: 0.00
    fr:
      zero: 0.00
    gb:
      zero: 0.00
    pl:
      zero: 0.00
    ar:
      zero: 0.00
    au:
      zero: 0.00
    mx:
      zero: 0.00
    se:
      zero: 0.00
    dk:
      zero: 0.00
    it:
      zero: 0.00
    cl:
      zero: 0.00
    hu:
      zero: 0.00
    pt:
      zero: 0.00
