AppBundle\Entity\ApiUser:
  attributes:
    username:
      groups: ['user', 'order']
    email:
      groups: ['user']
    addresses:
      groups: ['user']
    telephone:
      groups: ['order']
    roles:
      groups: ['user']

AppBundle\Entity\Sylius\Taxon:
  attributes:
    code:
      groups: ['restaurant']

Sylius\Component\Order\Model\Order:
  attributes:
    id:
      groups: ['order']
    restaurant:
      groups: ['order', 'order_create']
    shippingAddress:
      groups: ['order', 'order_create']
    shippedAt:
      groups: ['order', 'order_create']
    customer:
      groups: ['order']
    items:
      groups: ['order', 'order_create']
    total:
      groups: ['order']
    number:
      groups: ['order']
    itemsTotal:
      groups: ['order']
    taxTotal:
      groups: ['order']
    state:
      groups: ['order']
    notes:
      groups: ['order']
    createdAt:
      groups: ['order']
    timeline:
      groups: ['order_timeline']
    preparationExpectedAt:
      groups: ['order']
    pickupExpectedAt:
      groups: ['order']

Sylius\Component\Order\Model\OrderItem:
  attributes:
    id:
      groups: ['order']
    quantity:
      groups: ['order']
    total:
      groups: ['order']
    unitPrice:
      groups: ['order']

AppBundle\Entity\Sylius\OrderTimeline:
  attributes:
    preparationExpectedAt:
      groups: ['order_timeline']
    pickupExpectedAt:
      groups: ['order_timeline']
    dropoffExpectedAt:
      groups: ['order_timeline']

Sylius\Component\Product\Model\Product:
  attributes:
    id:
      groups: ['product']
    name:
      groups: ['product']
    code:
      groups: ['product']
    enabled:
      groups: ['product', 'product_update']
