AppBundle\Entity\Restaurant:
    type: entity
    table: restaurant
    repositoryClass: AppBundle\Entity\RestaurantRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
            hard_delete: false
    indexes:
        restaurant_enabled_index:
            columns: [ id, enabled ]
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        description:
            type: text
            nullable: true
        enabled:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            options:
                default: false
        depositRefundEnabled:
            type: boolean
            options:
                default: false
        depositRefundOptin:
            type: boolean
            options:
                default: 't'
        orderingDelayMinutes:
            type: integer
            unique: false
            nullable: false
            options:
                default: 0
        imageName:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
            column: image_name
        website:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        telephone:
            type: phone_number
            nullable: true
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        legalName:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: legal_name
        deliveryPerimeterExpression:
            type: string
            nullable: false
            unique: false
            options:
              default: 'distance < 3000'
        openingHours:
            type: json_array
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: opening_hours
        vatID:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: vat_id
        additionalProperties:
            type: json_array
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: additional_properties
        state:
            type: string
        stripeConnectRoles:
            type: json_array
            column: stripe_connect_roles
        deletedAt:
            type: datetime
            nullable: true
        exclusive:
            type: boolean
            options:
                default: false
        quotesAllowed:
            type: boolean
            column: quotes_allowed
            options:
                default: false
    manyToMany:
        servesCuisine:
            targetEntity: AppBundle\Entity\Cuisine
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinTable:
                name: restaurant_cuisine
                inverseJoinColumns:
                    -
                        name: cuisine_id
                        unique: false
                        nullable: true
                        referencedColumnName: id
                joinColumns:
                    -
                        name: restaurant_id
                        referencedColumnName: id
                        onDelete: CASCADE
            orderBy:
                name: ASC
        owners:
            targetEntity: AppBundle\Entity\ApiUser
            mappedBy: restaurants
        products:
            targetEntity: Sylius\Component\Product\Model\ProductInterface
            mappedBy: restaurant
            cascade:
                - persist
            joinTable:
                name: restaurant_product
                joinColumns:
                    restaurant_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    product_id:
                        referencedColumnName: id
                        unique: true
        productOptions:
            targetEntity: Sylius\Component\Product\Model\ProductOptionInterface
            cascade:
                - persist
            joinTable:
                name: restaurant_product_option
                inverseJoinColumns:
                    -
                        name: option_id
                        referencedColumnName: id
                joinColumns:
                    -
                        name: restaurant_id
                        referencedColumnName: id
        taxons:
            targetEntity: Sylius\Component\Taxonomy\Model\TaxonInterface
            cascade:
                - persist
            joinTable:
                name: restaurant_taxon
                inverseJoinColumns:
                    -
                        name: taxon_id
                        referencedColumnName: id
                joinColumns:
                    -
                        name: restaurant_id
                        referencedColumnName: id
    oneToOne:
        contract:
            targetEntity: AppBundle\Entity\Contract
            cascade:
                - persist
            fetch: LAZY
            mappedBy: restaurant
            inversedBy: null
            joinColumns: {  }
            orphanRemoval: false
        pledge:
            targetEntity: AppBundle\Entity\Restaurant\Pledge
            cascade:
                - all
            fetch: LAZY
            mappedBy: restaurant
            inversedBy: null
    manyToOne:
        address:
            targetEntity: AppBundle\Entity\Address
            cascade:
                - all
            fetch: EAGER
        activeMenuTaxon:
            targetEntity: Sylius\Component\Taxonomy\Model\TaxonInterface
            joinColumns:
                active_menu_taxon_id:
                    referencedColumnName: id
                    nullable: true
    oneToMany:
        closingRules:
            targetEntity: AppBundle\Entity\ClosingRule
            cascade:
                - all
            fetch: LAZY
            mappedBy: restaurant
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        preparationTimeRules:
            targetEntity: AppBundle\Entity\Restaurant\PreparationTimeRule
            cascade:
                - all
            mappedBy: restaurant
            orderBy:
                position: ASC
        orders:
            targetEntity: Sylius\Component\Order\Model\OrderInterface
            fetch: LAZY
            mappedBy: restaurant
        stripeAccounts:
            targetEntity: AppBundle\Entity\RestaurantStripeAccount
            mappedBy: restaurant
            cascade:
                - all
        reusablePackagings:
            targetEntity: AppBundle\Entity\ReusablePackaging
            mappedBy: restaurant
            cascade:
                - all
