AppBundle\Entity\Store:
    type: entity
    table: store
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
        enabled:
            type: boolean
            options:
                default: false
        imageName:
            type: string
            nullable: true
            precision: 0
            column: image_name
        website:
            type: string
            nullable: true
        telephone:
            type: phone_number
            nullable: true
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        legalName:
            type: string
            nullable: true
            column: legal_name
        openingHours:
            type: json_array
            nullable: true
            column: opening_hours
        vatID:
            type: string
            nullable: true
            column: vat_id
        additionalProperties:
            type: json_array
            nullable: true
            column: additional_properties
    oneToOne:
        address:
            targetEntity: AppBundle\Entity\Address
            cascade:
                - all
            fetch: LAZY
            joinColumns:
                address_id:
                    referencedColumnName: id
        token:
            targetEntity: AppBundle\Entity\Store\Token
            mappedBy: store
            cascade:
                - all
    manyToOne:
        stripeAccount:
            targetEntity: AppBundle\Entity\StripeAccount
            joinColumns:
                stripe_account_id:
                    referencedColumnName: id
        pricingRuleSet:
            targetEntity: AppBundle\Entity\Delivery\PricingRuleSet
            cascade:
                - persist
            fetch: LAZY
            joinColumns:
                pricing_rule_set_id:
                    referencedColumnName: id
    manyToMany:
        owners:
            targetEntity: AppBundle\Entity\ApiUser
            mappedBy: stores
    oneToMany:
        deliveries:
            targetEntity: AppBundle\Entity\Delivery
            mappedBy: store
            cascade:
                - persist
