AppBundle\Entity\Sylius\Product:
    type: entity
    table: sylius_product
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
            hard_delete: false
    fields:
        imageName:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
            column: image_name
        deletedAt:
            type: datetime
            nullable: true
        reusablePackagingEnabled:
            type: boolean
            options:
                default: false
        reusablePackagingUnit:
            type: float
            nullable: true
    manyToMany:
        restaurant:
            targetEntity: AppBundle\Entity\Restaurant
            inversedBy: products
            joinTable:
                name: restaurant_product
                joinColumns:
                    product_id:
                        referencedColumnName: id
                        unique: true
                inverseJoinColumns:
                    restaurant_id:
                        referencedColumnName: id
    manyToOne:
        reusablePackaging:
            targetEntity: AppBundle\Entity\ReusablePackaging
            joinColumns:
                reusable_packaging_id:
                    referencedColumnName: id
                    nullable: true
    oneToMany:
        options:
            targetEntity: AppBundle\Entity\Sylius\ProductOptions
            mappedBy: product
            cascade:
                - persist
                - remove
            orphanRemoval: true
