AppBundle\Entity\Sylius\Order:
    type: entity
    table: sylius_order
    fields:
        shippedAt:
            type: datetime
            column: shipped_at
            nullable: true
        reusablePackagingEnabled:
            type: boolean
            options:
                default: false
    manyToOne:
        customer:
            targetEntity: AppBundle\Entity\ApiUser
            joinColumns:
                customer_id:
                    referencedColumnName: id
                    nullable: true
        restaurant:
            targetEntity: AppBundle\Entity\Restaurant
            inversedBy: orders
            joinColumns:
                restaurant_id:
                    referencedColumnName: id
                    nullable: true
        shippingAddress:
            targetEntity: AppBundle\Entity\Address
            joinColumns:
                shipping_address_id:
                    referencedColumnName: id
                    nullable: true
            cascade:
                - all
        billingAddress:
            targetEntity: AppBundle\Entity\Address
            joinColumns:
                billing_address_id:
                    referencedColumnName: id
                    nullable: true
            cascade:
                - all
        channel:
            targetEntity: Sylius\Component\Channel\Model\ChannelInterface
            joinColumns:
                channel_id:
                    referencedColumnName: id
                    nullable: true
        promotionCoupon:
            targetEntity: Sylius\Component\Promotion\Model\PromotionCouponInterface
            joinColumns:
                promotion_coupon_id:
                    referencedColumnName: id
            cascade:
                - persist
    oneToMany:
        payments:
            targetEntity: AppBundle\Entity\StripePayment
            mappedBy: order
            orphanRemoval: true
            cascade:
                - all
        events:
            targetEntity: AppBundle\Entity\Sylius\OrderEvent
            mappedBy: order
            cascade:
                - all
    oneToOne:
        delivery:
            targetEntity: AppBundle\Entity\Delivery
            mappedBy: order
            cascade:
                - persist
        timeline:
            targetEntity: AppBundle\Entity\Sylius\OrderTimeline
            mappedBy: order
            cascade:
                - all
        receipt:
            targetEntity: AppBundle\Entity\Sylius\OrderReceipt
            mappedBy: order
            cascade:
                - persist
                - remove
    manyToMany:
        promotions:
            targetEntity: Sylius\Component\Promotion\Model\PromotionInterface
            joinTable:
                name: sylius_promotion_order
                joinColumns:
                    order_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    promotion_id:
                        referencedColumnName: id
            cascade:
                - persist
