services:

  _defaults:
    autowire: true
    autoconfigure: true

  AppBundle\Validator\Constraints\CartValidator:
    arguments: [ '@routing_service' ]
    tags:
      - { name: validator.constraint_validator }

  AppBundle\Validator\Constraints\DeliveryValidator:
    arguments: [ '@routing_service' ]
    tags:
      - { name: validator.constraint_validator }

  AppBundle\Validator\Constraints\OrderValidator:
    arguments:
      - '@routing_service'
      - '@coopcycle.expression_language'
      - '@coopcycle.shipping_date_filter'
    tags:
      - { name: validator.constraint_validator }

  AppBundle\Validator\Constraints\IsActivableRestaurantValidator:
    arguments: [ '@coopcycle.settings_manager' ]
    tags:
      - { name: validator.constraint_validator }

  AppBundle\Validator\Constraints\TaskValidator:
    arguments:
      - '@doctrine'
    tags:
      - { name: validator.constraint_validator }

  AppBundle\Validator\Constraints\CheckDeliveryValidator:
    tags:
      - { name: validator.constraint_validator }

  AppBundle\Validator\Constraints\ProductOptionValidator:
    tags:
      - { name: validator.constraint_validator }

  AppBundle\Validator\Constraints\LoopEatOrderValidator:
    tags:
      - { name: validator.constraint_validator }

  AppBundle\Validator\Constraints\PricingRuleValidator:
    tags:
      - { name: validator.constraint_validator }

  AppBundle\Validator\Constraints\UserWithSameEmailNotExistsValidator:
    tags:
      - { name: validator.constraint_validator }
